name: Send Mail on Push

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }} 
          subject: 'Push tehtud: ${{ github.repository }}'
          body: |
            Tere!

            Kehtestuse tegi: ${{ github.event.pusher.name }}
            Kehtestuse sõnum: ${{ github.event.head_commit.message }}

            Repo: ${{ github.repository }}
          to: 'doe481157@gmail.com'
          from: ${{ secrets.MAIL_USERNAME }}
